## Holds settings 
extends Node

const ACCESS_BUTTON_CLICK = 0
const ACCESS_CUE_VISUAL = 1

enum {
	INPUT_BUTTON_ON_SLIDE,
	INPUT_BUTTON_ON_CLICK_ONLY,
	CUE_VISUAL_ALWAYS,
	CUE_VISUAL_CONDITIONAL
}

const DEFAULT_SETTINGS := {
	ACCESS_BUTTON_CLICK: INPUT_BUTTON_ON_SLIDE,
	ACCESS_CUE_VISUAL: CUE_VISUAL_CONDITIONAL
	}

var settings = DEFAULT_SETTINGS.duplicate(true)
